/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiListenRouteImport } from './routes/api/listen'
import { Route as ApiRunRouteImport } from './routes/api/run'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListenRoute = ApiListenRouteImport.update({
  id: '/api/listen',
  path: '/api/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunRoute = ApiRunRouteImport.update({
  id: '/api/run',
  path: '/api/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/listen': typeof ApiListenRoute
  '/api/run': typeof ApiRunRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/listen': typeof ApiListenRoute
  '/api/run': typeof ApiRunRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/listen': typeof ApiListenRoute
  '/api/run': typeof ApiRunRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/listen' | '/api/run' | '/api/webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/listen' | '/api/run' | '/api/webhook'
  id: '__root__' | '/' | '/api/listen' | '/api/run' | '/api/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiListenRoute: typeof ApiListenRoute
  ApiRunRoute: typeof ApiRunRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listen': {
      id: '/api/listen'
      path: '/api/listen'
      fullPath: '/api/listen'
      preLoaderRoute: typeof ApiListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run': {
      id: '/api/run'
      path: '/api/run'
      fullPath: '/api/run'
      preLoaderRoute: typeof ApiRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiListenRoute: ApiListenRoute,
  ApiRunRoute: ApiRunRoute,
  ApiWebhookRoute: ApiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
